export const IPC_CHANNELS = {
  SELECT_PDF: 'select-pdf',
  GET_PDF_STREAM_URL: 'get-pdf-stream-url',
  PDF_REGISTER_PATH: 'pdf:register-path',
  CAPTURE_SCREEN: 'capture-screen',
  COPY_IMAGE: 'copy-image-to-clipboard',
  COPY_TEXT: 'copy-text-to-clipboard',
  OPEN_EXTERNAL: 'open-external',
  SHOW_PDF_CONTEXT_MENU: 'show-pdf-context-menu',
  TRIGGER_SCREENSHOT: 'trigger-screenshot',
  CHECK_FOR_UPDATES: 'check-for-updates',
  OPEN_RELEASES: 'open-releases-page',
  GET_APP_VERSION: 'get-app-version',
  FORCE_PASTE: 'force-paste-in-webview',
  SAVE_AI_CONFIG: 'save-ai-config',
  GET_AI_CONFIG: 'get-ai-config',
  DELETE_AI_CONFIG: 'delete-ai-config',
  // AI Registry & Automation (Main Process Data)
  GET_AI_REGISTRY: 'get-ai-registry',
  GET_AUTOMATION_SCRIPTS: 'get-automation-scripts',
  ADD_CUSTOM_AI: 'add-custom-ai',
  DELETE_CUSTOM_AI: 'delete-custom-ai',
  IS_AUTH_DOMAIN: 'is-auth-domain',
  // Quiz CLI Generation
  GENERATE_QUIZ_CLI: 'generate-quiz-cli',
  ASK_AI: 'ask-ai-assistant',
  GET_QUIZ_SETTINGS: 'get-quiz-settings',
  SAVE_QUIZ_SETTINGS: 'save-quiz-settings',
  CLEAR_CACHE: 'clear-cache',
  // Quiz Auth & CLI - Standardized
  GET_GEMINI_CLI_PATH: 'get-gemini-cli-path',
  OPEN_GEMINI_LOGIN: 'open-gemini-login',
  CHECK_GEMINI_AUTH: 'check-gemini-auth',
  GEMINI_LOGOUT: 'gemini-logout',
  // Gemini Web Session
  GEMINI_WEB_OPEN_LOGIN: 'gemini-web-open-login',
  GEMINI_WEB_STATUS: 'gemini-web-status',
  GEMINI_WEB_CHECK_NOW: 'gemini-web-check-now',
  GEMINI_WEB_REAUTH: 'gemini-web-reauth',
  GEMINI_WEB_RESET_PROFILE: 'gemini-web-reset-profile',
  GEMINI_WEB_SET_ENABLED: 'gemini-web-set-enabled',
  GEMINI_WEB_SET_ENABLED_APPS: 'gemini-web-set-enabled-apps',
  // App lifecycle
  APP_QUIT: 'app-quit'
}
