export const STORAGE_KEYS = {
  LEFT_PANEL_WIDTH: 'leftPanelWidth',
  LAST_SELECTED_AI: 'lastSelectedAI',
  AUTO_SEND_ENABLED: 'autoSendEnabled',
  ENABLED_MODELS: 'enabledModels',
  BUILT_IN_SITE_BOOTSTRAP: 'builtInSiteBootstrap',
  DEFAULT_AI_MODEL: 'defaultAiModel',
  PINNED_AI_TABS: 'pinnedAiTabs',
  SHOW_ONLY_ICONS: 'showOnlyIcons',
  BOTTOM_BAR_OPACITY: 'bottomBarOpacity',
  BOTTOM_BAR_SCALE: 'bottomBarScale',
  IS_LAYOUT_SWAPPED: 'isLayoutSwapped',
  BG_TYPE: 'bgType',
  BG_SOLID_COLOR: 'bgSolidColor',
  BG_ANIMATED_COLORS: 'bgAnimatedColors',
  BG_RANDOM_MODE: 'bgRandomMode',
  SELECTION_COLOR: 'selectionColor',
  APP_LANGUAGE: 'appLanguage',
  CUSTOM_PROMPTS: 'customPrompts',
  SELECTED_PROMPT_ID: 'selectedPromptId',
  LAST_PDF_READING: 'lastPdfReading'
} as const
